# **4. Introducción al uso de Arreglos con `numpy`**

`Numpy` (o *Numerical Python*) es uno de los modulos más importantes en Python, ya que muchos otros sistemas o modulos utilizan  arreglos de N-dimensiones  (`ndarray`) los cuales son la estrcutura de datos proncipal en este paquete. Además, este tipo de estrucutras son la base para casi todos los ecosistemas de computación científica en Python como son los modulos de procesamiento de datos, áljebra lineal, modelos estadísticos, machine learning y deep learning. 


## **4.1 Arreglos en `numpy`**

Los arreglos son estructuras de datos conformadas por una o multiples listas con valores homogéneos que permiten realizar operaciones matemáticas y estadísticas eficientemente. 

Para definir un arreglo debemos tener importar el modulo numpy de la siguiente forma:

In [1]:
import numpy as np

El modulo`numpy` se define con la palabra clave `np`. 

**Sintáxis**

Para definir un arregalo utilizaremos la función `array()` con la palabra clave :
```Python 
np.array(lista)
```

Lo anterior de define como arreglo de una , pero se puede tener tener arreglos de dos dimensiones:

```Python 
np.array([lista_1, lista_2, lista_3,...,lista_n])
```

Los arreglos de dos dimensiones se consideran **matrices** y son gran utilidad para la construcción de modelos estadísticos que utilicen vectores y matrices para su construcción

Ejemplos de definición de arreglos:

* Arreglo de una dimensión

In [6]:
#Definir arreglo 
array_1 = np.array( [100, 404, 404, 55, 44, 55, 150, 700, 1000, 38])
#Imprimir
print(array_1, type(array_1))

[ 100  404  404   55   44   55  150  700 1000   38] <class 'numpy.ndarray'>


* Arreglo de dos dimensiones

In [9]:
#Crear arreglo
array_2 = np.array([ [3,4,4] , 
                     [4,10,32],
                     [24,33,43] ])

print(array_2)

[[ 3  4  4]
 [ 4 10 32]
 [24 33 43]]


Una de las características más importante de los arreglos es que sólo recibe **valores homogéneos** en las listas, y si no son homogéneos los transforma. Por ejemplo.

In [12]:
#Crear arreglo
array_3 = np.array([ [True,False, True] , 
                     [4,10,32],
                     [24,33,43] ])


print(array_3)

[[ 1  0  1]
 [ 4 10 32]
 [24 33 43]]


### **4.1.1 Creación y manejo de arreglos**

### **4.1.1.1 Creación de arreglos**
En `numpy` existen una serie de funciones para crear arreglos que contengan ceros, unos, números generados de forma aleatoria, muestras a partir de distribuciones de probabilidad discretas y continuas, etc.

1. Para crear arreglos con zeros se utiliza la función `np.zeros(shape)` , en donde el argumento será el tamaño del arreglo de ceros de una dimensión:


In [19]:
#Crear arreglos de ceros 1D
array_ceros_1d = np.zeros(5)

print(array_ceros_1d)



[0. 0. 0. 0. 0.]


  * Para crear una matriz o arreglo de dos dimensiones:

In [21]:
#Crear arreglos de ceros de 2D 
array_ceros_2d = np.zeros((5,5))

print(array_ceros_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2. Para crear arreglos con el número uno se utiliza la función `np.ones(shape)` con la misma sintáxis que en la de los ceros:


In [27]:
#Crear arreglos de unos 1D
array_unos_1d = np.ones(5)

print(array_unos_1d)

#Crear arreglos de ceros de 2D 
array_unos_2d = np.ones((5,5))

print(array_unos_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3. Creación de arreglos de números aleatorios:

   La sintáxis será la siguiente: 

   ```Python  
   np.random.randint(inicio, final, tamaño)
   ```
 


In [34]:
#Definir arreglo 1D
array_random_1D = np.random.randint(0, 10, 5)
#Resultado
print( f"Arreglo de una dimensión:\n {array_random_1D}" )

#Definir arreglo 2D
array_random_2D = np.random.randint(0, 10, (5,5))
#Resultado
print( f"Arreglo de dos dimensiones o matriz:\n {array_random_2D}" )

Arreglo de una dimensión:
 [2 3 5 7 3]
Arreglo de dos dimensiones o matriz:
 [[7 9 4 5 1]
 [5 8 9 3 6]
 [3 2 4 2 9]
 [0 8 7 3 7]
 [6 9 8 8 3]]


3. Creación de un arreglo con muestra de variables alteorias a partir de una distribución binomial:

   La sintáxis será la siguiente: 

   ```Python  
   random.binomial(n, p, size=None)
   ```
   Donde: 

   `n`: Número de ensayos por experimento.

   `p`: Probabilidad de éxito en cada ensayo.

   `tamaño`: Número de experimentos independientes que se realizarán.


In [47]:
#Creación de arreglo
array_binom_1d = np.random.binomial(10, .5, size= 4)
#Imprimir resultado
print( f"Arreglo de una dimensión :\n {array_binom_1d}" )

#Creación de arreglo
array_binom_2d = np.random.binomial(10, .5, size= (4,5))
#Imprimir resultado

print( f"Arreglo de dos dimensiones :\n {array_binom_2d}" )

Arreglo de una dimensión :
 [6 3 3 2]
Arreglo de dos dimensiones :
 [[4 8 3 5 6]
 [6 9 8 5 5]
 [7 4 4 7 3]
 [4 8 7 3 2]]


Numpy ofrece una gran cantidad de funciones para crear muestreos de variables a aleatorias a partir de cierta distribución de probabilidad (las veremos más adelante). Para consultar todas las funciones disponibles:   [NumPy](https://numpy.org/)

### **4.1.1.2 Manejo de arreglos**

### **4.1.2 Aljebra lineal con numpy**

### **4.1.3 Funciones estadísticas aplicadas a los arreglos**