# **4. Introducción a `numpy`**

`Numpy` (o *Numerical Python*) es uno de los modulos más importantes en Python, ya que muchos otros sistemas o modulos utilizan  arreglos de N-dimensiones  (`ndarray`) los cuales son la estrcutura de datos proncipal en este paquete. Además, este tipo de estrucutras son la base para casi todos los ecosistemas de computación científica en Python como son los modulos de procesamiento de datos, áljebra lineal, modelos estadísticos, machine learning y deep learning. 


## **4.1 Arreglos en `numpy`**

Los arreglos son estructuras de datos conformadas por una o multiples listas con valores homogéneos que permiten realizar operaciones matemáticas y estadísticas eficientemente. 

Para definir un arreglo debemos tener importar el modulo numpy de la siguiente forma:

In [1]:
import numpy as np

El modulo`numpy` se define con la palabra clave `np`. 

**Sintáxis**

Para definir un arregalo utilizaremos la función `array()` con la palabra clave :
```Python 
np.array(lista)
```

Lo anterior de define como arreglo de una , pero se puede tener tener arreglos de dos dimensiones:

```Python 
np.array([lista_1, lista_2, lista_3,...,lista_n])
```

Los arreglos de dos dimensiones se consideran **matrices** y son gran utilidad para la construcción de modelos estadísticos que utilicen vectores y matrices para su construcción

Ejemplos de definición de arreglos:

* Arreglo de una dimensión

In [2]:
#Definir arreglo 
array_1 = np.array( [100, 404, 404, 55, 44, 55, 150, 700, 1000, 38])
#Imprimir
print(array_1, type(array_1))

[ 100  404  404   55   44   55  150  700 1000   38] <class 'numpy.ndarray'>


* Arreglo de dos dimensiones

In [3]:
#Crear arreglo
array_2 = np.array([ [3,4,4] , 
                     [4,10,32],
                     [24,33,43] ])

print(array_2)

[[ 3  4  4]
 [ 4 10 32]
 [24 33 43]]


Una de las características más importante de los arreglos es que sólo recibe **valores homogéneos** en las listas, y si no son homogéneos los transforma. Por ejemplo.

In [4]:
#Crear arreglo
array_3 = np.array([ [True,False, True] , 
                     [4,10,32],
                     [24,33,43] ])


print(array_3)

[[ 1  0  1]
 [ 4 10 32]
 [24 33 43]]


### **4.1.1 Creación y manejo de arreglos**

### **4.1.1.1 Creación de arreglos**
En `numpy` existen una serie de funciones para crear arreglos que contengan ceros, unos, números generados de forma aleatoria, muestras a partir de distribuciones de probabilidad discretas y continuas, etc.

1. Para crear arreglos con zeros se utiliza la función `np.zeros(shape)` , en donde el argumento será el tamaño del arreglo de ceros de una dimensión:


In [5]:
#Crear arreglos de ceros 1D
array_ceros_1d = np.zeros(5)

print(array_ceros_1d)



[0. 0. 0. 0. 0.]


  * Para crear una matriz o arreglo de dos dimensiones:

In [6]:
#Crear arreglos de ceros de 2D 
array_ceros_2d = np.zeros((5,5))

print(array_ceros_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2. Para crear arreglos con el número uno se utiliza la función `np.ones(shape)` con la misma sintáxis que en la de los ceros:


In [7]:
#Crear arreglos de unos 1D
array_unos_1d = np.ones(5)

print(array_unos_1d)

#Crear arreglos de ceros de 2D 
array_unos_2d = np.ones((5,5))

print(array_unos_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3. Creación de arreglos de números aleatorios:

   La sintáxis será la siguiente: 

   ```Python  
   np.random.randint(inicio, final, tamaño)
   ```
 


In [8]:
#Definir arreglo 1D
array_random_1D = np.random.randint(0, 10, 5)
#Resultado
print( f"Arreglo de una dimensión:\n {array_random_1D}" )

#Definir arreglo 2D
array_random_2D = np.random.randint(0, 10, (5,5))
#Resultado
print( f"Arreglo de dos dimensiones o matriz:\n {array_random_2D}" )

Arreglo de una dimensión:
 [8 5 0 6 7]
Arreglo de dos dimensiones o matriz:
 [[8 9 2 5 3]
 [2 4 3 2 4]
 [5 9 2 4 3]
 [5 0 5 8 9]
 [4 5 5 7 2]]


3. Creación de un arreglo con muestra de variables alteorias a partir de una distribución binomial:

   La sintáxis será la siguiente: 

   ```Python  
   random.binomial(n, p, size=None)
   ```
   Donde: 

   `n`: Número de ensayos por experimento.

   `p`: Probabilidad de éxito en cada ensayo.

   `tamaño`: Número de experimentos independientes que se realizarán.


In [9]:
#Creación de arreglo
array_binom_1d = np.random.binomial(10, .5, size= 4)
#Imprimir resultado
print( f"Arreglo de una dimensión :\n {array_binom_1d}" )

#Creación de arreglo
array_binom_2d = np.random.binomial(10, .5, size= (4,5))
#Imprimir resultado

print( f"Arreglo de dos dimensiones :\n {array_binom_2d}" )

Arreglo de una dimensión :
 [3 4 4 5]
Arreglo de dos dimensiones :
 [[6 4 3 3 9]
 [3 4 7 6 7]
 [5 7 4 7 7]
 [7 3 6 5 4]]


Numpy ofrece una gran cantidad de funciones para crear muestreos de variables a aleatorias a partir de cierta distribución de probabilidad (las veremos más adelante). Para consultar todas las funciones disponibles:   [NumPy](https://numpy.org/)

### **4.1.1.2 Manejo de arreglos**

Como mencionamos, los arreglos en numpy se crean a  partir de listas por lo que heredan las caráterísticas de **mutabilidad**. En otras palabras, podemos acceder, sustituir, agregar y eliminar elementos de un arreglo en numpy.

**Tamaño del arreglo y dimensión**

Para saber el tamaño (número de elementos) y las dimensiones que tiene los arreglos con los que trabajamos se utilizan una serie de funciones de de base así como del modulo numpy.

* Las funciones `size` y  `np.size()` muestran el número de elementos independientemente si trabajamos con arreglos de una o más dimensiones. 

  Ejemplo:


In [35]:
#Tamaño del arreglo
print(array_binom_1d.size)

#Tamaño del arreglo
print(np.size(array_binom_2d))

4
20


* La función `shape` regresa una tupla que indica la dimensión del arreglo.
   
   Ejemplo:

In [37]:
#Tamaño del arreglo
print(array_binom_1d.shape)

#Tamaño del arreglo
print(array_binom_2d.shape)

(4,)
(4, 5)


**Acceso a elementos**

Para acceder a los elementos de un arreglo usamos la misma sintáxis que en las lista. Especificamente, se utilizan los corchetes cuadrados:


* Arreglo de una dimensión 

   ```Python
   array_1d[posición]
   
   ```

* Para el arreglo de dos dimensiones (matriz) se utiliza la posición fila, columna para extraer el elemento de interes

   ```Python
   matriz[posición_fila, posición_col]
   
   ```
Ejemplo:

In [21]:
#Acceder primer valor de arrelo de una dimensión 
print(array_binom_1d[0])
#Acceder primer elemento de una matriz
print(array_binom_2d[0,0])

3
6


Para acceder a multiples elementos, al igual que en las listas, se utilizan `:` con los cuales definiremos el rango de elementos a lque queremos acceder.

* Arreglo de una dimensión 

   ```Python

   array_1d[posición_inicial : posición_final ]
   
   ```

* Para el arreglo de dos dimensiones (matriz) se utiliza la posición fila, columna para extraer el elemento de interes

   ```Python
   matriz[posición_fila_inicial : posición_fila_final , posición_col_inicial :posición_col_final ]
   
   ```

   Ejemplo:

In [47]:
#Acceder a primeros dos valores 
print(array_binom_1d[0:2])

#Acceder a primeras dos filas completas
print(array_binom_2d[0:2, 0:])

[3 4]
[[6 4 3 3 9]
 [3 4 7 6 7]]


In [46]:
#Otra forma de acceder a arreglos es por listas anidadas 
array_binom_2d[[0,1], :]

array([[6, 4, 3, 3, 9],
       [3, 4, 7, 6, 7]], dtype=int32)

**Sustitución de elementos**

Dado que un arreglo es mutable podemos reemplazar sus elementos  a partir de la selección de un elemento o un rango de elementos y asignando nuevos valores con el signo =.

**Sintáxis** 

```Python
   array[elemento] = [elemento_nuevo]
   ```
Ejemplo:

In [53]:
print("Seguimos con el arreglo de muestreo de una distribución binomial", array_binom_1d)
#Remplazar valor 1 con un 4
array_binom_1d[0] = 4
print(array_binom_1d)

Seguimos con el arreglo de muestreo de una distribución binomial [4 4 4 5]
[4 4 4 5]


In [62]:
print("Seguimos con el arreglo de muestreo de una distribución binomial \n",  array_binom_2d)

#Reemplazar fila dos por 1 
array_binom_2d[1,:] = 1
#array_binom_2d[1,:] = [1,1,1,1,1]
print(array_binom_2d)


Seguimos con el arreglo de muestreo de una distribución binomial 
 [[6 4 3 3 9]
 [0 0 0 0 0]
 [5 7 4 7 7]
 [7 3 6 5 4]]
[[6 4 3 3 9]
 [1 1 1 1 1]
 [5 7 4 7 7]
 [7 3 6 5 4]]


In [63]:
#Reemplazar todo con 0 
array_binom_2d[:] = 0
print(array_binom_2d)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


**Agregar elementos**

Para agregar elementos nuevos a un arreglo se utiliza la función `np.append()` es la versión numpy de la que utilizamos con las listas (`append()`).

**Sintáxis** 
```Python
   array_new = np.append(array_old, 1)
   ```
Ejemplo:

In [65]:
print("Seguimos con el arreglo de muestreo de una distribución binomial", array_binom_1d)
#Agregar un valor 0 al arreglo
array_binom_1d = np.append(array_binom_1d,0)
print(array_binom_1d)

Seguimos con el arreglo de muestreo de una distribución binomial [4 4 4 5]
[4 4 4 5 0]


PAra 

### **4.1.2 Aljebra lineal con numpy**

### **4.1.3 Funciones estadísticas aplicadas a los arreglos**